@url = http://localhost:8080

@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjYXZlLXNlcnZlciIsInN1YiI6ImFkbWluIiwiYXV0aG9yaXRpZXMiOiJBRE1JTiIsImV4cCI6MTY4MzA0OTE0OX0.ZWCYCOEq-maprXsZiuj8ifIdJasOKEsqdBM8sp_3RYA

###

POST {{url}}/api/authenticate HTTP/1.1
content-type: application/json

{
  "username": "admin",
  "password": "root"
}

###

POST {{url}}/api/create_user HTTP/1.1
content-type: application/json

{
  "username": "user",
  "password": "pass"
}

###

GET {{url}}/api/save HTTP/1.1
Authorization: Bearer {{token}}

###

POST {{url}}/api/save HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "user":"admin",
  "saveDate":"2023-04-23T18:25:43.511Z",
  "saveName":"New Game",
  "level":"Test"
}

###

PUT {{url}}/api/save HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id":1,
  "user":"admin",
  "saveDate":"2023-03-23T18:25:43.511Z",
  "saveName":"New Gamer",
  "level":"Test2"
}

###

DELETE {{url}}/api/save HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id":1,
  "user":"admin",
  "saveDate":"2023-04-23T18:25:43.511Z",
  "saveName":"New Game",
  "level":"Test"
}

###
